### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by RicoBlaze8** [AresEntertainmentLtd/mcuuid#2]
Please I have a server and I use your API. Everytime there's an issue. Now the problem is that every account catch an error: Invalid Username. Resolve.

**Comment by RicoBlaze8** [comment]
Can you resolve?

**Comment by Incrementing** [comment]
Please can you provide more detail about the issue your having. 
What is the URL that you're requesting data from?
What are some examples of usernames that you're sending to the API?
Does your code output any stacktraces?
What lang are you writing the API in?

**Comment by RicoBlaze8** [comment]
https://api.mcuuid.com/v1/uuid/davidkiller21
output
{
    "message": "Invalid username",
    "rate": 2
}

**Comment by RicoBlaze8** [comment]
On every nickname

**Comment by Incrementing** [comment]
Let me take a look at the logs, there seems to be an error contacting Mojangs API.

**Comment by RicoBlaze8** [comment]
Ok

**Comment by RicoBlaze8** [comment]
Have you found any error?

**Comment by RicoBlaze8** [comment]
Maybe you resolved the error

**Comment by Incrementing** [comment]
Yes, the error has been solved thank you for reporting it.

Input:
https://api.mcuuid.com/v1/uuid/davidkiller21
Output:
`{
    "username": "davidkiller21",
    "uuid": {
        "formatted": "f98afdcd-22e4-4313-859c-c4afb9dddda5",
        "stripped": "f98afdcd22e44313859cc4afb9dddda5"
    },
    "live": false,
    "age": 66,
    "rate": 1
}
`
