### ISSUE TITLE
PROBLEM

### ISSUE THREAD

**Issue by RicoBlaze8** [AresEntertainmentLtd/mcuuid#4]
Mate I have to open a server WITH YOUR API, but api.mcuuid.com IS OFFLINE!! RESOLVE.

**Comment by RicoBlaze8** [comment]
It is urgent!!

**Comment by RicoBlaze8** [comment]
MATE JESUS

**Comment by RicoBlaze8** [comment]
I CANNOT WAIT FOR YOU!!!!!

**Comment by RicoBlaze8** [comment]
I'll remove this api for my server

**Comment by Incrementing** [comment]
I'm pretty sure, I banned your IP for spam hitting the rate limit. If not re-open this.
